// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"

	"github.com/kadragon/portfolio-manager/internal/datex"
	"github.com/kadragon/portfolio-manager/internal/ktime"
	"github.com/kadragon/portfolio-manager/internal/numeric"
	"github.com/kadragon/portfolio-manager/internal/uuidx"
)

type Account struct {
	ID           uuidx.UUID
	Name         string
	CashBalance  numeric.Decimal
	CreatedAt    ktime.Time
	UpdatedAt    ktime.Time
	KisAccountNo sql.NullString
	KisApiKeyID  sql.NullInt64
	AccountType  sql.NullString
}

type Deposit struct {
	ID          uuidx.UUID
	Amount      numeric.Decimal
	DepositDate datex.Date
	Note        sql.NullString
	CreatedAt   ktime.Time
	UpdatedAt   ktime.Time
}

type Group struct {
	ID               uuidx.UUID
	Name             string
	TargetPercentage float64
	CreatedAt        ktime.Time
	UpdatedAt        ktime.Time
}

type Holding struct {
	ID        uuidx.UUID
	AccountID uuidx.UUID
	StockID   uuidx.UUID
	Quantity  numeric.Decimal
	CreatedAt ktime.Time
	UpdatedAt ktime.Time
}

type OrderExecution struct {
	ID          uuidx.UUID
	Ticker      string
	Side        string
	Quantity    int64
	Currency    string
	Exchange    sql.NullString
	Status      string
	Message     string
	RawResponse sql.NullString
	CreatedAt   ktime.Time
}

type Stock struct {
	ID         uuidx.UUID
	Ticker     string
	GroupID    uuidx.UUID
	Exchange   sql.NullString
	CreatedAt  ktime.Time
	UpdatedAt  ktime.Time
	Name       string
	AssetClass sql.NullString
}

type StockPrice struct {
	ID        uuidx.UUID
	Ticker    string
	Price     numeric.Decimal
	Currency  string
	Name      string
	Exchange  sql.NullString
	PriceDate datex.Date
	CreatedAt ktime.Time
	UpdatedAt ktime.Time
}
