// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"

	"github.com/kadragon/portfolio-manager/internal/ktime"
	"github.com/kadragon/portfolio-manager/internal/uuidx"
)

const createGroup = `-- name: CreateGroup :one

INSERT INTO groups (id, name, target_percentage, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, target_percentage, created_at, updated_at
`

type CreateGroupParams struct {
	ID               uuidx.UUID
	Name             string
	TargetPercentage float64
	CreatedAt        ktime.Time
	UpdatedAt        ktime.Time
}

// Group queries (Phase 1).
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.TargetPercentage,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuidx.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, target_percentage, created_at, updated_at FROM groups WHERE id = ?
`

func (q *Queries) GetGroup(ctx context.Context, id uuidx.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, target_percentage, created_at, updated_at FROM groups
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetPercentage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = ?, target_percentage = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, target_percentage, created_at, updated_at
`

type UpdateGroupParams struct {
	Name             string
	TargetPercentage float64
	UpdatedAt        ktime.Time
	ID               uuidx.UUID
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroup,
		arg.Name,
		arg.TargetPercentage,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
