// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/kadragon/portfolio-manager/internal/datex"
	"github.com/kadragon/portfolio-manager/internal/ktime"
	"github.com/kadragon/portfolio-manager/internal/numeric"
	"github.com/kadragon/portfolio-manager/internal/uuidx"
)

const createAccount = `-- name: CreateAccount :one

INSERT INTO accounts (id, name, cash_balance, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, cash_balance, created_at, updated_at, kis_account_no, kis_api_key_id, account_type, toss_account_seq
`

type CreateAccountParams struct {
	ID          uuidx.UUID
	Name        string
	CashBalance numeric.Decimal
	CreatedAt   ktime.Time
	UpdatedAt   ktime.Time
}

// Account queries (Phase 3).
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.Name,
		arg.CashBalance,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KisAccountNo,
		&i.KisApiKeyID,
		&i.AccountType,
		&i.TossAccountSeq,
	)
	return i, err
}

const createDeposit = `-- name: CreateDeposit :one

INSERT INTO deposits (id, amount, deposit_date, note, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, amount, deposit_date, note, created_at, updated_at
`

type CreateDepositParams struct {
	ID          uuidx.UUID
	Amount      numeric.Decimal
	DepositDate datex.Date
	Note        sql.NullString
	CreatedAt   ktime.Time
	UpdatedAt   ktime.Time
}

// Deposit queries (Phase 5).
func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, createDeposit,
		arg.ID,
		arg.Amount,
		arg.DepositDate,
		arg.Note,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.DepositDate,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one

INSERT INTO groups (id, name, target_percentage, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, target_percentage, created_at, updated_at
`

type CreateGroupParams struct {
	ID               uuidx.UUID
	Name             string
	TargetPercentage float64
	CreatedAt        ktime.Time
	UpdatedAt        ktime.Time
}

// Group queries (Phase 1).
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.TargetPercentage,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHolding = `-- name: CreateHolding :one

INSERT INTO holdings (id, account_id, stock_id, quantity, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, account_id, stock_id, quantity, created_at, updated_at
`

type CreateHoldingParams struct {
	ID        uuidx.UUID
	AccountID uuidx.UUID
	StockID   uuidx.UUID
	Quantity  numeric.Decimal
	CreatedAt ktime.Time
	UpdatedAt ktime.Time
}

// Holding queries (Phase 4).
func (q *Queries) CreateHolding(ctx context.Context, arg CreateHoldingParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, createHolding,
		arg.ID,
		arg.AccountID,
		arg.StockID,
		arg.Quantity,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StockID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderExecution = `-- name: CreateOrderExecution :one

INSERT INTO order_executions (id, ticker, side, quantity, currency, exchange, status, message, raw_response, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, ticker, side, quantity, currency, exchange, status, message, raw_response, created_at
`

type CreateOrderExecutionParams struct {
	ID          uuidx.UUID
	Ticker      string
	Side        string
	Quantity    int64
	Currency    string
	Exchange    sql.NullString
	Status      string
	Message     string
	RawResponse sql.NullString
	CreatedAt   ktime.Time
}

// Phase 7 queries.
func (q *Queries) CreateOrderExecution(ctx context.Context, arg CreateOrderExecutionParams) (OrderExecution, error) {
	row := q.db.QueryRowContext(ctx, createOrderExecution,
		arg.ID,
		arg.Ticker,
		arg.Side,
		arg.Quantity,
		arg.Currency,
		arg.Exchange,
		arg.Status,
		arg.Message,
		arg.RawResponse,
		arg.CreatedAt,
	)
	var i OrderExecution
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.Side,
		&i.Quantity,
		&i.Currency,
		&i.Exchange,
		&i.Status,
		&i.Message,
		&i.RawResponse,
		&i.CreatedAt,
	)
	return i, err
}

const createStock = `-- name: CreateStock :one

INSERT INTO stocks (id, ticker, group_id, exchange, created_at, updated_at, name, asset_class, security_group)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, ticker, group_id, exchange, created_at, updated_at, name, asset_class, security_group
`

type CreateStockParams struct {
	ID            uuidx.UUID
	Ticker        string
	GroupID       uuidx.UUID
	Exchange      sql.NullString
	CreatedAt     ktime.Time
	UpdatedAt     ktime.Time
	Name          string
	AssetClass    sql.NullString
	SecurityGroup sql.NullString
}

// Stock queries (Phase 2).
func (q *Queries) CreateStock(ctx context.Context, arg CreateStockParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, createStock,
		arg.ID,
		arg.Ticker,
		arg.GroupID,
		arg.Exchange,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.AssetClass,
		arg.SecurityGroup,
	)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.GroupID,
		&i.Exchange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.AssetClass,
		&i.SecurityGroup,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuidx.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const deleteDeposit = `-- name: DeleteDeposit :exec
DELETE FROM deposits WHERE id = ?
`

func (q *Queries) DeleteDeposit(ctx context.Context, id uuidx.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDeposit, id)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuidx.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const deleteHolding = `-- name: DeleteHolding :exec
DELETE FROM holdings WHERE id = ?
`

func (q *Queries) DeleteHolding(ctx context.Context, id uuidx.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteHolding, id)
	return err
}

const deleteHoldingsByAccount = `-- name: DeleteHoldingsByAccount :exec
DELETE FROM holdings WHERE account_id = ?
`

func (q *Queries) DeleteHoldingsByAccount(ctx context.Context, accountID uuidx.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteHoldingsByAccount, accountID)
	return err
}

const deleteStock = `-- name: DeleteStock :exec
DELETE FROM stocks WHERE id = ?
`

func (q *Queries) DeleteStock(ctx context.Context, id uuidx.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStock, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, name, cash_balance, created_at, updated_at, kis_account_no, kis_api_key_id, account_type, toss_account_seq FROM accounts WHERE id = ?
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuidx.UUID) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KisAccountNo,
		&i.KisApiKeyID,
		&i.AccountType,
		&i.TossAccountSeq,
	)
	return i, err
}

const getDepositByDate = `-- name: GetDepositByDate :one
SELECT id, amount, deposit_date, note, created_at, updated_at FROM deposits WHERE deposit_date = ?
`

func (q *Queries) GetDepositByDate(ctx context.Context, depositDate datex.Date) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, getDepositByDate, depositDate)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.DepositDate,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepositByID = `-- name: GetDepositByID :one
SELECT id, amount, deposit_date, note, created_at, updated_at FROM deposits WHERE id = ?
`

func (q *Queries) GetDepositByID(ctx context.Context, id uuidx.UUID) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, getDepositByID, id)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.DepositDate,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFirstDepositDate = `-- name: GetFirstDepositDate :one
SELECT deposit_date FROM deposits ORDER BY deposit_date ASC LIMIT 1
`

func (q *Queries) GetFirstDepositDate(ctx context.Context) (datex.Date, error) {
	row := q.db.QueryRowContext(ctx, getFirstDepositDate)
	var deposit_date datex.Date
	err := row.Scan(&deposit_date)
	return deposit_date, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, target_percentage, created_at, updated_at FROM groups WHERE id = ?
`

func (q *Queries) GetGroup(ctx context.Context, id uuidx.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHoldingByID = `-- name: GetHoldingByID :one
SELECT id, account_id, stock_id, quantity, created_at, updated_at FROM holdings WHERE id = ?
`

func (q *Queries) GetHoldingByID(ctx context.Context, id uuidx.UUID) (Holding, error) {
	row := q.db.QueryRowContext(ctx, getHoldingByID, id)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StockID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestStockPriceByTicker = `-- name: GetLatestStockPriceByTicker :one
SELECT id, ticker, price, currency, name, exchange, price_date, created_at, updated_at FROM stock_prices WHERE ticker = ? ORDER BY price_date DESC LIMIT 1
`

func (q *Queries) GetLatestStockPriceByTicker(ctx context.Context, ticker string) (StockPrice, error) {
	row := q.db.QueryRowContext(ctx, getLatestStockPriceByTicker, ticker)
	var i StockPrice
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.Price,
		&i.Currency,
		&i.Name,
		&i.Exchange,
		&i.PriceDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockByID = `-- name: GetStockByID :one
SELECT id, ticker, group_id, exchange, created_at, updated_at, name, asset_class, security_group FROM stocks WHERE id = ?
`

func (q *Queries) GetStockByID(ctx context.Context, id uuidx.UUID) (Stock, error) {
	row := q.db.QueryRowContext(ctx, getStockByID, id)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.GroupID,
		&i.Exchange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.AssetClass,
		&i.SecurityGroup,
	)
	return i, err
}

const getStockByTicker = `-- name: GetStockByTicker :one
SELECT id, ticker, group_id, exchange, created_at, updated_at, name, asset_class, security_group FROM stocks WHERE ticker = ?
`

func (q *Queries) GetStockByTicker(ctx context.Context, ticker string) (Stock, error) {
	row := q.db.QueryRowContext(ctx, getStockByTicker, ticker)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.GroupID,
		&i.Exchange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.AssetClass,
		&i.SecurityGroup,
	)
	return i, err
}

const getStockPriceByTickerAndDate = `-- name: GetStockPriceByTickerAndDate :one
SELECT id, ticker, price, currency, name, exchange, price_date, created_at, updated_at FROM stock_prices WHERE ticker = ? AND price_date = ?
`

type GetStockPriceByTickerAndDateParams struct {
	Ticker    string
	PriceDate datex.Date
}

func (q *Queries) GetStockPriceByTickerAndDate(ctx context.Context, arg GetStockPriceByTickerAndDateParams) (StockPrice, error) {
	row := q.db.QueryRowContext(ctx, getStockPriceByTickerAndDate, arg.Ticker, arg.PriceDate)
	var i StockPrice
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.Price,
		&i.Currency,
		&i.Name,
		&i.Exchange,
		&i.PriceDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockPriceOnOrBeforeDate = `-- name: GetStockPriceOnOrBeforeDate :one
SELECT id, ticker, price, currency, name, exchange, price_date, created_at, updated_at FROM stock_prices WHERE ticker = ? AND price_date <= ? ORDER BY price_date DESC LIMIT 1
`

type GetStockPriceOnOrBeforeDateParams struct {
	Ticker    string
	PriceDate datex.Date
}

func (q *Queries) GetStockPriceOnOrBeforeDate(ctx context.Context, arg GetStockPriceOnOrBeforeDateParams) (StockPrice, error) {
	row := q.db.QueryRowContext(ctx, getStockPriceOnOrBeforeDate, arg.Ticker, arg.PriceDate)
	var i StockPrice
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.Price,
		&i.Currency,
		&i.Name,
		&i.Exchange,
		&i.PriceDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, cash_balance, created_at, updated_at, kis_account_no, kis_api_key_id, account_type, toss_account_seq FROM accounts
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CashBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KisAccountNo,
			&i.KisApiKeyID,
			&i.AccountType,
			&i.TossAccountSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllHoldings = `-- name: ListAllHoldings :many

SELECT id, account_id, stock_id, quantity, created_at, updated_at FROM holdings
`

// Phase 6 queries.
func (q *Queries) ListAllHoldings(ctx context.Context) ([]Holding, error) {
	rows, err := q.db.QueryContext(ctx, listAllHoldings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Holding{}
	for rows.Next() {
		var i Holding
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.StockID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllStocks = `-- name: ListAllStocks :many
SELECT id, ticker, group_id, exchange, created_at, updated_at, name, asset_class, security_group FROM stocks
`

func (q *Queries) ListAllStocks(ctx context.Context) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, listAllStocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stock{}
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.GroupID,
			&i.Exchange,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.AssetClass,
			&i.SecurityGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeposits = `-- name: ListDeposits :many
SELECT id, amount, deposit_date, note, created_at, updated_at FROM deposits ORDER BY deposit_date DESC
`

func (q *Queries) ListDeposits(ctx context.Context) ([]Deposit, error) {
	rows, err := q.db.QueryContext(ctx, listDeposits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deposit{}
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.DepositDate,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, target_percentage, created_at, updated_at FROM groups
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetPercentage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoldingsByAccount = `-- name: ListHoldingsByAccount :many
SELECT id, account_id, stock_id, quantity, created_at, updated_at FROM holdings WHERE account_id = ?
`

func (q *Queries) ListHoldingsByAccount(ctx context.Context, accountID uuidx.UUID) ([]Holding, error) {
	rows, err := q.db.QueryContext(ctx, listHoldingsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Holding{}
	for rows.Next() {
		var i Holding
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.StockID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentOrderExecutions = `-- name: ListRecentOrderExecutions :many
SELECT id, ticker, side, quantity, currency, exchange, status, message, raw_response, created_at FROM order_executions ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListRecentOrderExecutions(ctx context.Context, limit int64) ([]OrderExecution, error) {
	rows, err := q.db.QueryContext(ctx, listRecentOrderExecutions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderExecution{}
	for rows.Next() {
		var i OrderExecution
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.Side,
			&i.Quantity,
			&i.Currency,
			&i.Exchange,
			&i.Status,
			&i.Message,
			&i.RawResponse,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStocksByGroup = `-- name: ListStocksByGroup :many
SELECT id, ticker, group_id, exchange, created_at, updated_at, name, asset_class, security_group FROM stocks WHERE group_id = ?
`

func (q *Queries) ListStocksByGroup(ctx context.Context, groupID uuidx.UUID) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, listStocksByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stock{}
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.GroupID,
			&i.Exchange,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.AssetClass,
			&i.SecurityGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = ?, cash_balance = ?, kis_account_no = ?, kis_api_key_id = ?, account_type = ?, toss_account_seq = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, cash_balance, created_at, updated_at, kis_account_no, kis_api_key_id, account_type, toss_account_seq
`

type UpdateAccountParams struct {
	Name           string
	CashBalance    numeric.Decimal
	KisAccountNo   sql.NullString
	KisApiKeyID    sql.NullInt64
	AccountType    sql.NullString
	TossAccountSeq sql.NullInt64
	UpdatedAt      ktime.Time
	ID             uuidx.UUID
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.Name,
		arg.CashBalance,
		arg.KisAccountNo,
		arg.KisApiKeyID,
		arg.AccountType,
		arg.TossAccountSeq,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KisAccountNo,
		&i.KisApiKeyID,
		&i.AccountType,
		&i.TossAccountSeq,
	)
	return i, err
}

const updateAccountNameCash = `-- name: UpdateAccountNameCash :one
UPDATE accounts SET name = ?, cash_balance = ?, updated_at = ? WHERE id = ?
RETURNING id, name, cash_balance, created_at, updated_at, kis_account_no, kis_api_key_id, account_type, toss_account_seq
`

type UpdateAccountNameCashParams struct {
	Name        string
	CashBalance numeric.Decimal
	UpdatedAt   ktime.Time
	ID          uuidx.UUID
}

func (q *Queries) UpdateAccountNameCash(ctx context.Context, arg UpdateAccountNameCashParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccountNameCash,
		arg.Name,
		arg.CashBalance,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KisAccountNo,
		&i.KisApiKeyID,
		&i.AccountType,
		&i.TossAccountSeq,
	)
	return i, err
}

const updateDeposit = `-- name: UpdateDeposit :one
UPDATE deposits SET amount = ?, deposit_date = ?, note = ?, updated_at = ? WHERE id = ?
RETURNING id, amount, deposit_date, note, created_at, updated_at
`

type UpdateDepositParams struct {
	Amount      numeric.Decimal
	DepositDate datex.Date
	Note        sql.NullString
	UpdatedAt   ktime.Time
	ID          uuidx.UUID
}

func (q *Queries) UpdateDeposit(ctx context.Context, arg UpdateDepositParams) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, updateDeposit,
		arg.Amount,
		arg.DepositDate,
		arg.Note,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.DepositDate,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDepositWithoutNote = `-- name: UpdateDepositWithoutNote :one
UPDATE deposits SET amount = ?, deposit_date = ?, updated_at = ? WHERE id = ?
RETURNING id, amount, deposit_date, note, created_at, updated_at
`

type UpdateDepositWithoutNoteParams struct {
	Amount      numeric.Decimal
	DepositDate datex.Date
	UpdatedAt   ktime.Time
	ID          uuidx.UUID
}

func (q *Queries) UpdateDepositWithoutNote(ctx context.Context, arg UpdateDepositWithoutNoteParams) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, updateDepositWithoutNote,
		arg.Amount,
		arg.DepositDate,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.DepositDate,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = ?, target_percentage = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, target_percentage, created_at, updated_at
`

type UpdateGroupParams struct {
	Name             string
	TargetPercentage float64
	UpdatedAt        ktime.Time
	ID               uuidx.UUID
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroup,
		arg.Name,
		arg.TargetPercentage,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHolding = `-- name: UpdateHolding :one
UPDATE holdings SET quantity = ?, updated_at = ? WHERE id = ?
RETURNING id, account_id, stock_id, quantity, created_at, updated_at
`

type UpdateHoldingParams struct {
	Quantity  numeric.Decimal
	UpdatedAt ktime.Time
	ID        uuidx.UUID
}

func (q *Queries) UpdateHolding(ctx context.Context, arg UpdateHoldingParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, updateHolding, arg.Quantity, arg.UpdatedAt, arg.ID)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StockID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStockAssetClass = `-- name: UpdateStockAssetClass :one
UPDATE stocks SET asset_class = ?, updated_at = ? WHERE id = ?
RETURNING id, ticker, group_id, exchange, created_at, updated_at, name, asset_class, security_group
`

type UpdateStockAssetClassParams struct {
	AssetClass sql.NullString
	UpdatedAt  ktime.Time
	ID         uuidx.UUID
}

func (q *Queries) UpdateStockAssetClass(ctx context.Context, arg UpdateStockAssetClassParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, updateStockAssetClass, arg.AssetClass, arg.UpdatedAt, arg.ID)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.GroupID,
		&i.Exchange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.AssetClass,
		&i.SecurityGroup,
	)
	return i, err
}

const updateStockExchange = `-- name: UpdateStockExchange :one
UPDATE stocks SET exchange = ?, updated_at = ? WHERE id = ?
RETURNING id, ticker, group_id, exchange, created_at, updated_at, name, asset_class, security_group
`

type UpdateStockExchangeParams struct {
	Exchange  sql.NullString
	UpdatedAt ktime.Time
	ID        uuidx.UUID
}

func (q *Queries) UpdateStockExchange(ctx context.Context, arg UpdateStockExchangeParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, updateStockExchange, arg.Exchange, arg.UpdatedAt, arg.ID)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.GroupID,
		&i.Exchange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.AssetClass,
		&i.SecurityGroup,
	)
	return i, err
}

const updateStockGroup = `-- name: UpdateStockGroup :one
UPDATE stocks SET group_id = ?, updated_at = ? WHERE id = ?
RETURNING id, ticker, group_id, exchange, created_at, updated_at, name, asset_class, security_group
`

type UpdateStockGroupParams struct {
	GroupID   uuidx.UUID
	UpdatedAt ktime.Time
	ID        uuidx.UUID
}

func (q *Queries) UpdateStockGroup(ctx context.Context, arg UpdateStockGroupParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, updateStockGroup, arg.GroupID, arg.UpdatedAt, arg.ID)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.GroupID,
		&i.Exchange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.AssetClass,
		&i.SecurityGroup,
	)
	return i, err
}

const updateStockName = `-- name: UpdateStockName :one
UPDATE stocks SET name = ?, updated_at = ? WHERE id = ?
RETURNING id, ticker, group_id, exchange, created_at, updated_at, name, asset_class, security_group
`

type UpdateStockNameParams struct {
	Name      string
	UpdatedAt ktime.Time
	ID        uuidx.UUID
}

func (q *Queries) UpdateStockName(ctx context.Context, arg UpdateStockNameParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, updateStockName, arg.Name, arg.UpdatedAt, arg.ID)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.GroupID,
		&i.Exchange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.AssetClass,
		&i.SecurityGroup,
	)
	return i, err
}

const updateStockSecurityGroup = `-- name: UpdateStockSecurityGroup :one
UPDATE stocks SET security_group = ?, updated_at = ? WHERE id = ?
RETURNING id, ticker, group_id, exchange, created_at, updated_at, name, asset_class, security_group
`

type UpdateStockSecurityGroupParams struct {
	SecurityGroup sql.NullString
	UpdatedAt     ktime.Time
	ID            uuidx.UUID
}

func (q *Queries) UpdateStockSecurityGroup(ctx context.Context, arg UpdateStockSecurityGroupParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, updateStockSecurityGroup, arg.SecurityGroup, arg.UpdatedAt, arg.ID)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.GroupID,
		&i.Exchange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.AssetClass,
		&i.SecurityGroup,
	)
	return i, err
}

const updateStockTicker = `-- name: UpdateStockTicker :one
UPDATE stocks SET ticker = ?, updated_at = ? WHERE id = ?
RETURNING id, ticker, group_id, exchange, created_at, updated_at, name, asset_class, security_group
`

type UpdateStockTickerParams struct {
	Ticker    string
	UpdatedAt ktime.Time
	ID        uuidx.UUID
}

func (q *Queries) UpdateStockTicker(ctx context.Context, arg UpdateStockTickerParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, updateStockTicker, arg.Ticker, arg.UpdatedAt, arg.ID)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.GroupID,
		&i.Exchange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.AssetClass,
		&i.SecurityGroup,
	)
	return i, err
}

const upsertStockPrice = `-- name: UpsertStockPrice :one
INSERT INTO stock_prices (id, ticker, price, currency, name, exchange, price_date, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(ticker, price_date) DO UPDATE SET
    price=excluded.price,
    currency=excluded.currency,
    name=CASE WHEN excluded.name != '' THEN excluded.name ELSE stock_prices.name END,
    exchange=excluded.exchange,
    updated_at=excluded.updated_at
RETURNING id, ticker, price, currency, name, exchange, price_date, created_at, updated_at
`

type UpsertStockPriceParams struct {
	ID        uuidx.UUID
	Ticker    string
	Price     numeric.Decimal
	Currency  string
	Name      string
	Exchange  sql.NullString
	PriceDate datex.Date
	CreatedAt ktime.Time
	UpdatedAt ktime.Time
}

func (q *Queries) UpsertStockPrice(ctx context.Context, arg UpsertStockPriceParams) (StockPrice, error) {
	row := q.db.QueryRowContext(ctx, upsertStockPrice,
		arg.ID,
		arg.Ticker,
		arg.Price,
		arg.Currency,
		arg.Name,
		arg.Exchange,
		arg.PriceDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i StockPrice
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.Price,
		&i.Currency,
		&i.Name,
		&i.Exchange,
		&i.PriceDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
