// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/kadragon/portfolio-manager/internal/datex"
	"github.com/kadragon/portfolio-manager/internal/ktime"
	"github.com/kadragon/portfolio-manager/internal/numeric"
	"github.com/kadragon/portfolio-manager/internal/uuidx"
)

const createAccount = `-- name: CreateAccount :one

INSERT INTO accounts (id, name, cash_balance, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, cash_balance, created_at, updated_at, kis_account_no, kis_api_key_id
`

type CreateAccountParams struct {
	ID          uuidx.UUID
	Name        string
	CashBalance numeric.Decimal
	CreatedAt   ktime.Time
	UpdatedAt   ktime.Time
}

// Account queries (Phase 3).
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.Name,
		arg.CashBalance,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KisAccountNo,
		&i.KisApiKeyID,
	)
	return i, err
}

const createDeposit = `-- name: CreateDeposit :one

INSERT INTO deposits (id, amount, deposit_date, note, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, amount, deposit_date, note, created_at, updated_at
`

type CreateDepositParams struct {
	ID          uuidx.UUID
	Amount      numeric.Decimal
	DepositDate datex.Date
	Note        sql.NullString
	CreatedAt   ktime.Time
	UpdatedAt   ktime.Time
}

// Deposit queries (Phase 5).
func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, createDeposit,
		arg.ID,
		arg.Amount,
		arg.DepositDate,
		arg.Note,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.DepositDate,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one

INSERT INTO groups (id, name, target_percentage, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, target_percentage, created_at, updated_at
`

type CreateGroupParams struct {
	ID               uuidx.UUID
	Name             string
	TargetPercentage float64
	CreatedAt        ktime.Time
	UpdatedAt        ktime.Time
}

// Group queries (Phase 1).
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.TargetPercentage,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHolding = `-- name: CreateHolding :one

INSERT INTO holdings (id, account_id, stock_id, quantity, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, account_id, stock_id, quantity, created_at, updated_at
`

type CreateHoldingParams struct {
	ID        uuidx.UUID
	AccountID uuidx.UUID
	StockID   uuidx.UUID
	Quantity  numeric.Decimal
	CreatedAt ktime.Time
	UpdatedAt ktime.Time
}

// Holding queries (Phase 4).
func (q *Queries) CreateHolding(ctx context.Context, arg CreateHoldingParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, createHolding,
		arg.ID,
		arg.AccountID,
		arg.StockID,
		arg.Quantity,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StockID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStock = `-- name: CreateStock :one

INSERT INTO stocks (id, ticker, group_id, exchange, created_at, updated_at, name)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, ticker, group_id, exchange, created_at, updated_at, name
`

type CreateStockParams struct {
	ID        uuidx.UUID
	Ticker    string
	GroupID   uuidx.UUID
	Exchange  sql.NullString
	CreatedAt ktime.Time
	UpdatedAt ktime.Time
	Name      string
}

// Stock queries (Phase 2).
func (q *Queries) CreateStock(ctx context.Context, arg CreateStockParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, createStock,
		arg.ID,
		arg.Ticker,
		arg.GroupID,
		arg.Exchange,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
	)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.GroupID,
		&i.Exchange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id uuidx.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const deleteDeposit = `-- name: DeleteDeposit :exec
DELETE FROM deposits WHERE id = ?
`

func (q *Queries) DeleteDeposit(ctx context.Context, id uuidx.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDeposit, id)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuidx.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const deleteHolding = `-- name: DeleteHolding :exec
DELETE FROM holdings WHERE id = ?
`

func (q *Queries) DeleteHolding(ctx context.Context, id uuidx.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteHolding, id)
	return err
}

const deleteHoldingsByAccount = `-- name: DeleteHoldingsByAccount :exec
DELETE FROM holdings WHERE account_id = ?
`

func (q *Queries) DeleteHoldingsByAccount(ctx context.Context, accountID uuidx.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteHoldingsByAccount, accountID)
	return err
}

const deleteStock = `-- name: DeleteStock :exec
DELETE FROM stocks WHERE id = ?
`

func (q *Queries) DeleteStock(ctx context.Context, id uuidx.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStock, id)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, name, cash_balance, created_at, updated_at, kis_account_no, kis_api_key_id FROM accounts WHERE id = ?
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuidx.UUID) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KisAccountNo,
		&i.KisApiKeyID,
	)
	return i, err
}

const getDepositByDate = `-- name: GetDepositByDate :one
SELECT id, amount, deposit_date, note, created_at, updated_at FROM deposits WHERE deposit_date = ?
`

func (q *Queries) GetDepositByDate(ctx context.Context, depositDate datex.Date) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, getDepositByDate, depositDate)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.DepositDate,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepositByID = `-- name: GetDepositByID :one
SELECT id, amount, deposit_date, note, created_at, updated_at FROM deposits WHERE id = ?
`

func (q *Queries) GetDepositByID(ctx context.Context, id uuidx.UUID) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, getDepositByID, id)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.DepositDate,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, target_percentage, created_at, updated_at FROM groups WHERE id = ?
`

func (q *Queries) GetGroup(ctx context.Context, id uuidx.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHoldingByID = `-- name: GetHoldingByID :one
SELECT id, account_id, stock_id, quantity, created_at, updated_at FROM holdings WHERE id = ?
`

func (q *Queries) GetHoldingByID(ctx context.Context, id uuidx.UUID) (Holding, error) {
	row := q.db.QueryRowContext(ctx, getHoldingByID, id)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StockID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockByID = `-- name: GetStockByID :one
SELECT id, ticker, group_id, exchange, created_at, updated_at, name FROM stocks WHERE id = ?
`

func (q *Queries) GetStockByID(ctx context.Context, id uuidx.UUID) (Stock, error) {
	row := q.db.QueryRowContext(ctx, getStockByID, id)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.GroupID,
		&i.Exchange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const getStockByTicker = `-- name: GetStockByTicker :one
SELECT id, ticker, group_id, exchange, created_at, updated_at, name FROM stocks WHERE ticker = ?
`

func (q *Queries) GetStockByTicker(ctx context.Context, ticker string) (Stock, error) {
	row := q.db.QueryRowContext(ctx, getStockByTicker, ticker)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.GroupID,
		&i.Exchange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, cash_balance, created_at, updated_at, kis_account_no, kis_api_key_id FROM accounts
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CashBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.KisAccountNo,
			&i.KisApiKeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllStocks = `-- name: ListAllStocks :many
SELECT id, ticker, group_id, exchange, created_at, updated_at, name FROM stocks
`

func (q *Queries) ListAllStocks(ctx context.Context) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, listAllStocks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stock{}
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.GroupID,
			&i.Exchange,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeposits = `-- name: ListDeposits :many
SELECT id, amount, deposit_date, note, created_at, updated_at FROM deposits ORDER BY deposit_date DESC
`

func (q *Queries) ListDeposits(ctx context.Context) ([]Deposit, error) {
	rows, err := q.db.QueryContext(ctx, listDeposits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deposit{}
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.DepositDate,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, target_percentage, created_at, updated_at FROM groups
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TargetPercentage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHoldingsByAccount = `-- name: ListHoldingsByAccount :many
SELECT id, account_id, stock_id, quantity, created_at, updated_at FROM holdings WHERE account_id = ?
`

func (q *Queries) ListHoldingsByAccount(ctx context.Context, accountID uuidx.UUID) ([]Holding, error) {
	rows, err := q.db.QueryContext(ctx, listHoldingsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Holding{}
	for rows.Next() {
		var i Holding
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.StockID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStocksByGroup = `-- name: ListStocksByGroup :many
SELECT id, ticker, group_id, exchange, created_at, updated_at, name FROM stocks WHERE group_id = ?
`

func (q *Queries) ListStocksByGroup(ctx context.Context, groupID uuidx.UUID) ([]Stock, error) {
	rows, err := q.db.QueryContext(ctx, listStocksByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Stock{}
	for rows.Next() {
		var i Stock
		if err := rows.Scan(
			&i.ID,
			&i.Ticker,
			&i.GroupID,
			&i.Exchange,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = ?, cash_balance = ?, kis_account_no = ?, kis_api_key_id = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, cash_balance, created_at, updated_at, kis_account_no, kis_api_key_id
`

type UpdateAccountParams struct {
	Name         string
	CashBalance  numeric.Decimal
	KisAccountNo sql.NullString
	KisApiKeyID  sql.NullInt64
	UpdatedAt    ktime.Time
	ID           uuidx.UUID
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.Name,
		arg.CashBalance,
		arg.KisAccountNo,
		arg.KisApiKeyID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KisAccountNo,
		&i.KisApiKeyID,
	)
	return i, err
}

const updateAccountNameCash = `-- name: UpdateAccountNameCash :one
UPDATE accounts SET name = ?, cash_balance = ?, updated_at = ? WHERE id = ?
RETURNING id, name, cash_balance, created_at, updated_at, kis_account_no, kis_api_key_id
`

type UpdateAccountNameCashParams struct {
	Name        string
	CashBalance numeric.Decimal
	UpdatedAt   ktime.Time
	ID          uuidx.UUID
}

func (q *Queries) UpdateAccountNameCash(ctx context.Context, arg UpdateAccountNameCashParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccountNameCash,
		arg.Name,
		arg.CashBalance,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CashBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.KisAccountNo,
		&i.KisApiKeyID,
	)
	return i, err
}

const updateDeposit = `-- name: UpdateDeposit :one
UPDATE deposits SET amount = ?, deposit_date = ?, note = ?, updated_at = ? WHERE id = ?
RETURNING id, amount, deposit_date, note, created_at, updated_at
`

type UpdateDepositParams struct {
	Amount      numeric.Decimal
	DepositDate datex.Date
	Note        sql.NullString
	UpdatedAt   ktime.Time
	ID          uuidx.UUID
}

func (q *Queries) UpdateDeposit(ctx context.Context, arg UpdateDepositParams) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, updateDeposit,
		arg.Amount,
		arg.DepositDate,
		arg.Note,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.DepositDate,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDepositWithoutNote = `-- name: UpdateDepositWithoutNote :one
UPDATE deposits SET amount = ?, deposit_date = ?, updated_at = ? WHERE id = ?
RETURNING id, amount, deposit_date, note, created_at, updated_at
`

type UpdateDepositWithoutNoteParams struct {
	Amount      numeric.Decimal
	DepositDate datex.Date
	UpdatedAt   ktime.Time
	ID          uuidx.UUID
}

func (q *Queries) UpdateDepositWithoutNote(ctx context.Context, arg UpdateDepositWithoutNoteParams) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, updateDepositWithoutNote,
		arg.Amount,
		arg.DepositDate,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.DepositDate,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = ?, target_percentage = ?, updated_at = ?
WHERE id = ?
RETURNING id, name, target_percentage, created_at, updated_at
`

type UpdateGroupParams struct {
	Name             string
	TargetPercentage float64
	UpdatedAt        ktime.Time
	ID               uuidx.UUID
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, updateGroup,
		arg.Name,
		arg.TargetPercentage,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TargetPercentage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHolding = `-- name: UpdateHolding :one
UPDATE holdings SET quantity = ?, updated_at = ? WHERE id = ?
RETURNING id, account_id, stock_id, quantity, created_at, updated_at
`

type UpdateHoldingParams struct {
	Quantity  numeric.Decimal
	UpdatedAt ktime.Time
	ID        uuidx.UUID
}

func (q *Queries) UpdateHolding(ctx context.Context, arg UpdateHoldingParams) (Holding, error) {
	row := q.db.QueryRowContext(ctx, updateHolding, arg.Quantity, arg.UpdatedAt, arg.ID)
	var i Holding
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StockID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStockExchange = `-- name: UpdateStockExchange :one
UPDATE stocks SET exchange = ?, updated_at = ? WHERE id = ?
RETURNING id, ticker, group_id, exchange, created_at, updated_at, name
`

type UpdateStockExchangeParams struct {
	Exchange  sql.NullString
	UpdatedAt ktime.Time
	ID        uuidx.UUID
}

func (q *Queries) UpdateStockExchange(ctx context.Context, arg UpdateStockExchangeParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, updateStockExchange, arg.Exchange, arg.UpdatedAt, arg.ID)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.GroupID,
		&i.Exchange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const updateStockGroup = `-- name: UpdateStockGroup :one
UPDATE stocks SET group_id = ?, updated_at = ? WHERE id = ?
RETURNING id, ticker, group_id, exchange, created_at, updated_at, name
`

type UpdateStockGroupParams struct {
	GroupID   uuidx.UUID
	UpdatedAt ktime.Time
	ID        uuidx.UUID
}

func (q *Queries) UpdateStockGroup(ctx context.Context, arg UpdateStockGroupParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, updateStockGroup, arg.GroupID, arg.UpdatedAt, arg.ID)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.GroupID,
		&i.Exchange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const updateStockName = `-- name: UpdateStockName :one
UPDATE stocks SET name = ?, updated_at = ? WHERE id = ?
RETURNING id, ticker, group_id, exchange, created_at, updated_at, name
`

type UpdateStockNameParams struct {
	Name      string
	UpdatedAt ktime.Time
	ID        uuidx.UUID
}

func (q *Queries) UpdateStockName(ctx context.Context, arg UpdateStockNameParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, updateStockName, arg.Name, arg.UpdatedAt, arg.ID)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.GroupID,
		&i.Exchange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const updateStockTicker = `-- name: UpdateStockTicker :one
UPDATE stocks SET ticker = ?, updated_at = ? WHERE id = ?
RETURNING id, ticker, group_id, exchange, created_at, updated_at, name
`

type UpdateStockTickerParams struct {
	Ticker    string
	UpdatedAt ktime.Time
	ID        uuidx.UUID
}

func (q *Queries) UpdateStockTicker(ctx context.Context, arg UpdateStockTickerParams) (Stock, error) {
	row := q.db.QueryRowContext(ctx, updateStockTicker, arg.Ticker, arg.UpdatedAt, arg.ID)
	var i Stock
	err := row.Scan(
		&i.ID,
		&i.Ticker,
		&i.GroupID,
		&i.Exchange,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
